name: Generate Product Pages

on:
  push:
    paths:
      - generate.js
      - template/**
      - .github/workflows/generate-products.yml
  # --- Tambahkan bagian ini untuk mengizinkan eksekusi manual dari UI ---
  workflow_dispatch:
    inputs:
      # Anda bisa menambahkan input opsional di sini jika ingin memberikan parameter saat memicu manual.
      # Contoh:
      force_regeneration:
        description: 'Paksa regenerasi semua halaman (abaikan perubahan file)'
        required: false
        default: false
        type: boolean
  # --- Akhir penambahan ---

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate and commit product pages

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install node-fetch@2

    - name: Run generator
      # Anda bisa menggunakan input dari workflow_dispatch di sini jika diperlukan
      run: |
        if ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force_regeneration == 'true' }}; then
          echo "Memaksa regenerasi penuh..."
          # Anda mungkin perlu menambahkan logika di generate.js untuk menangani mode "force" ini
          node generate.js --force
        else
          node generate.js
        fi

    - name: Configure Git for Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        # Tidak perlu set-url lagi, actions/checkout@v3 sudah menanganinya dengan benar

    - name: Commit and Push Changes
      run: |
        # Periksa apakah ada perubahan pada direktori products/
        git add products/
        git diff-index --quiet HEAD || git commit -m "Auto-generate product pages [skip ci]"
        
        # Hanya push jika ada commit baru
        if [ "$(git log -1 --pretty=format:%s)" != "Auto-generate product pages [skip ci]" ]; then
          echo "Tidak ada perubahan baru untuk di-commit."
        else
          git push origin main
        fi